repos:
  # - repo: https://github.com/ambv/black
  #   rev: stable
  #   hooks:
  #     - id: black
  #       language_vesion: python3.11
  #       stages: [commit]
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: ['--ignore=E203, E226, E501, E503, F403, F401, F405, C101, Q000, E2, E129, E402, B950']
        additional_dependencies:
          - flake8-bugbear
          - flake8-builtins
          - flake8-coding
          - flake8-import-order
          - flake8-polyfill
          - flake8-quotes
        stages: [commit]

# - repo: local
#   hooks:
#   - id: pytest
#     name: pytest
#     language: system
#     entry: pytest
#     pass_filenames: false
#     always_run: true
#     stages: [push]

