services:

  redis:
    restart: unless-stopped
    image: redis:7.0.5-alpine 
    expose:
        - 6379
    networks:
      - live 

  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: daphne app.asgi:application -b 0.0.0.0 -p 8000 
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
      # - ./app/static:/home/app/web/staticfiles
      # - ./app/media:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis
    networks:
      - live
    restart: always

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles      
      # - ./app/static:/home/app/web/staticfiles
      # - ./app/media:/home/app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web
    networks:
      - live    

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    networks:
      - live


volumes:
  postgres_data:
  static_volume:
  media_volume:
  # static_volume: ./app/static/
  # media_volume: ./app/media/

networks:
  live: