# version: '3.8'

services:
  redis:  
    # restart: unless-stopped
    image: redis:7.0.5-alpine
    hostname: redis
    expose:
        - 6379
    networks:
      - live 

  
  web:
    build: ./app    
    # command: python manage.py runserver 0.0.0.0:8000 
    command: python manage.py runserver 0.0.0.0:8000 --settings=app.settingsdir.development 
    # command: python manage.py runserver
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
    networks:
      - live        

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
    networks:
      - live   

volumes:
  postgres_data:

networks:
  live:    