name: chat
on: [pull_request, workflow_all]

jobs:
  quality-assurance:
    name: Quality Assurance
    runs-on: ubuntu-latest
    container: python:3.10.4-buster

    services:
      db:
        image: postgres:14.2-alpine
        env:
          POSTGRES_DB: 
          POSTGRES_USER:
          POSTGRES_PASSWORD:
    steps:
      - uses: actions/checkout@v2
      - name: Install poetry
        uses: avatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.4.2
      
      - name: Install dependencies
        run: make install && make install-pre-commit
      
      - name: Lint
        run: make lint
      
      - name: Test
        run: make test