name: Quality Assurance
on: [pull_request, workflow_call]

jobs:
  quality-assurance:
    name: Quality Assurance
    runs-on: ubuntu-latest
    container: python:3.11.4-slim-buster

    services:
      db:
        image: postgres:15
        env:
          POSTGRES_DB: hello_django
          POSTGRES_USER: hello_django
          POSTGRES_PASSWORD: hello_django_dev

    steps:
      - name: Install Git
        run: apt-get update && apt-get install -y git
      
      - name: Verify Git installation
        run: git --version

      - uses: actions/checkout@v2
      
      - name: Give ownership
        run: git config --global --add safe.directory /__w/rtchat/rtchat
        
      - name: Debug repository contents
        run: |
          ls -la
          pwd
          git status

      - name: Install make
        run: apt-get update && apt-get install -y make            

      - name: Install Dependencies
        run: make install && make install-pre-commit

      - name: Lint
        run: make lint

      - name: Test
        run: make test
        # env:
        #   COOKING_CORE_SETTING_DATABASES: '{"default":{"HOST":"db"}}'
        #   COOKING_CORE_SETTING_LOCAL_SETTINGS_PATH: './cooking_core/project/settings/templates/settings.github.py'
